### ISSUE TITLE
虽然不知道怎么用，但是还是支持一下。

### ISSUE THREAD

**Issue by qweqaz0071** [mgsky1/DDNS#1]
好厉害，能搭建个cenos 运行吗

**Comment by mgsky1** [comment]
最近在忙考试，没看到😂，sorry~
首先感谢支持！
Python是跨平台的，在centos上肯定可以的，只要保证centos有Python3和项目所需要的库就行~
一些前提条件，比如域名啊，还有自己的宽带地址是公网ip啊，之类的，也是要满足的~
