### ISSUE TITLE
无法使用绝对路径执行DDNS.py

### ISSUE THREAD

**Issue by lsl061085** [mgsky1/DDNS#13]
打算添加到crontab定时任务执行脚本的时候发现任务无法执行，手动进入src目录执行python3 DDNS.py是可以正常执行的，请帮忙看看是什么问题，谢谢。
![image](https://user-images.githubusercontent.com/28956825/55476669-c9d08c80-5649-11e9-8ea9-51c7ff0063e0.png)

**Comment by Carliels** [comment]
Utils.py 中获取读取配置文件路径问题，可替换成实际文件所在绝对路径即可

**Comment by lsl061085** [comment]
> Utils.py中获取读取配置文件路径问题，可替换成实际文件所在绝对路径即可

谢谢您的回复，我刚写成sh脚本来解决这个绝对路径的问题了。

**Comment by shishixiu** [comment]
> 
> 
> > Utils.py中获取读取配置文件路径问题，可替换成实际文件所在绝对路径即可
> 
> 谢谢您的回复，我刚写成sh脚本来解决这个绝对路径的问题了。
大佬能分享下你的方法吗

**Comment by shishixiu** [comment]
> 
> 
> Utils.py 中获取读取配置文件路径问题，可替换成实际文件所在绝对路径即可

大佬能举个实例吗
