### ISSUE TITLE
 请问No such file or directory: 'config.json'是怎么回事

### ISSUE THREAD

**Issue by Xianglos** [mgsky1/DDNS#15]
![image](https://user-images.githubusercontent.com/33227442/56895172-cd292d80-6aba-11e9-9750-5276b93e7058.png)

![image](https://user-images.githubusercontent.com/33227442/56895130-abc84180-6aba-11e9-9d59-58c64e56725f.png)

**Comment by mgsky1** [comment]
我看你截图中的目录是`/etc/ddns`，而源码在src目录下，试着在`/etc/ddns/src`目录下运行，程序会在当前目录中寻找`config.json`。所以会出现找不到文件

**Comment by Xianglos** [comment]
感谢回复。问题已解决。查看源文件可知，使用了相对路径访问config.json文件，所以需要在src目录下执行。
-------- 原始信息 --------发件人： Martin Huang <notifications@github.com> 日期: 2019/5/1  12:03  (GMT+08:00) 收件人： mgsky1/DDNS <DDNS@noreply.github.com> 抄送： Xianglos <834294022@qq.com>, Author <author@noreply.github.com> 主题： Re: [mgsky1/DDNS]  请问No such file or directory: 'config.json'是怎么回事 (#15) 我看你截图中的目录是/etc/ddns，而源码在src目录下，试着在/etc/ddns/src目录下运行，程序会在当前目录中寻找config.json。所以会出现找不到文件



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mgsky1/DDNS","title":"mgsky1/DDNS","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mgsky1/DDNS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mgsky1 in #15: 我看你截图中的目录是`/etc/ddns`，而源码在src目录下，试着在`/etc/ddns/src`目录下运行，程序会在当前目录中寻找`config.json`。所以会出现找不到文件"}],"action":{"name":"View Issue","url":"https://github.com/mgsky1/DDNS/issues/15#issuecomment-488206149"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/mgsky1/DDNS/issues/15#issuecomment-488206149",

"url": "https://github.com/mgsky1/DDNS/issues/15#issuecomment-488206149",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
