### ISSUE TITLE
使用ipv6报json.decoder.JSONDecodeError错误

### ISSUE THREAD

**Issue by AnzhiZhang** [mgsky1/DDNS#28]
我使用时出现以下错误
```text
Traceback (most recent call last):
  File "DDNS.py", line 49, in <module>
    result = DDNS(isipv6)
  File "DDNS.py", line 21, in DDNS
    ip = Utils.getRealIPv6()
  File "/usr/bin/DDNS/src/Utils.py", line 27, in getRealIPv6
    ip = IpGetter.getRealIpV6(url)
  File "/usr/bin/DDNS/src/IpGetter.py", line 72, in getRealIpV6
    jsonData = json.loads(data)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

命令参数为 `python DDNS.py -6`，系统为树莓派版 `Ubuntu 20.04.2 LTS`，使用 `python3`，正常安装了 `aliyun-python-sdk-core-v3`

**Comment by pirder** [comment]
> 我使用时出现以下错误
> 
> ```
> Traceback (most recent call last):
>   File "DDNS.py", line 49, in <module>
>     result = DDNS(isipv6)
>   File "DDNS.py", line 21, in DDNS
>     ip = Utils.getRealIPv6()
>   File "/usr/bin/DDNS/src/Utils.py", line 27, in getRealIPv6
>     ip = IpGetter.getRealIpV6(url)
>   File "/usr/bin/DDNS/src/IpGetter.py", line 72, in getRealIpV6
>     jsonData = json.loads(data)
>   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
>     raise JSONDecodeError("Extra data", s, end)
> json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
> ```
> 
> 命令参数为 `python DDNS.py -6`，系统为树莓派版 `Ubuntu 20.04.2 LTS`，使用 `python3`，正常安装了 `aliyun-python-sdk-core-v3`


我改写了一些 你把这段代码修改上去 
```
def getIpPageV6():
    url = "https://v6.ident.me/.json"
    response = request.urlopen(url,timeout=60)
    html = response.read().decode('utf-8')
    htm = {}
    htm['address'] = html
    HTL = json.dumps(htm)
    return HTL
```
[IpGetter.py.zip](https://github.com/mgsky1/DDNS/files/7363927/IpGetter.py.zip)
